# This is a basic workflow to help you get started with Actions

name: for CRs, build pelican but don't publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Checkout Theme
        uses: actions/checkout@v2
        with:
          repository: timothycrosley/attila
          path: attila
          
      - name: Install Theme
        run: |
          pelican-themes -i attila
          
      - name: Run Pelican
        id: run-pelican
        run: |
          pelican
